language: c
compiler:
  - clang
  - gcc
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - sudo apt-get install apt-transport-https python-docutils
  - curl -s https://repo.varnish-cache.org/ubuntu/GPG-key.txt |
    sudo apt-key add -
  - echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-4.1" |
    sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get update
  - sudo apt-get install varnish libvarnishapi-dev
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra" &&
    make check VERBOSE=1
